-- MySQL Script generated by MySQL Workbench
-- Sun May  1 00:48:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Educacion` (
  `idEducacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `desde` VARCHAR(45) NOT NULL,
  `hasta` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEducacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `acercaDeMi` VARCHAR(255) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RedesSociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RedesSociales` (
  `idRedesSociales` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `link` VARCHAR(100) NULL,
  PRIMARY KEY (`idRedesSociales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personas_RedesSociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personas_RedesSociales` (
  `Persona_idPersona` INT NOT NULL,
  `RedesSociales_idRedesSociales` INT NOT NULL,
  INDEX `fk_Personas_RedesSociales_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  INDEX `fk_Personas_RedesSociales_RedesSociales1_idx` (`RedesSociales_idRedesSociales` ASC) VISIBLE,
  PRIMARY KEY (`Persona_idPersona`, `RedesSociales_idRedesSociales`),
  CONSTRAINT `fk_Personas_RedesSociales_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personas_RedesSociales_RedesSociales1`
    FOREIGN KEY (`RedesSociales_idRedesSociales`)
    REFERENCES `mydb`.`RedesSociales` (`idRedesSociales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ExperienciaLaboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ExperienciaLaboral` (
  `idExperienciaLaboral` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `desde` VARCHAR(10) NOT NULL,
  `hasta` VARCHAR(10) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idExperienciaLaboral`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyectos` (
  `idProyectos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idProyectos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skills` (
  `idSkills` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `porcentaje` INT NOT NULL,
  PRIMARY KEY (`idSkills`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personas_ExperienciaLaboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personas_ExperienciaLaboral` (
  `Persona_id` INT NOT NULL,
  `ExperienciaLaboral_id` INT NOT NULL,
  INDEX `fk_Personas_ExperienciaLaboral_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  INDEX `fk_Personas_ExperienciaLaboral_ExperienciaLaboral1_idx` (`ExperienciaLaboral_id` ASC) VISIBLE,
  PRIMARY KEY (`Persona_id`, `ExperienciaLaboral_id`),
  CONSTRAINT `fk_Personas_ExperienciaLaboral_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personas_ExperienciaLaboral_ExperienciaLaboral1`
    FOREIGN KEY (`ExperienciaLaboral_id`)
    REFERENCES `mydb`.`ExperienciaLaboral` (`idExperienciaLaboral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Educacion_Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Educacion_Persona` (
  `Educacion_id` INT NOT NULL,
  `Persona_id` INT NOT NULL,
  INDEX `fk_Educacion_Persona_Educacion_idx` (`Educacion_id` ASC) VISIBLE,
  INDEX `fk_Educacion_Persona_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  PRIMARY KEY (`Educacion_id`, `Persona_id`),
  CONSTRAINT `fk_Educacion_Persona_Educacion`
    FOREIGN KEY (`Educacion_id`)
    REFERENCES `mydb`.`Educacion` (`idEducacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Educacion_Persona_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona_Skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona_Skills` (
  `Persona_id` INT NOT NULL,
  `Skills_id` INT NOT NULL,
  INDEX `fk_Persona_Skills_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  INDEX `fk_Persona_Skills_Skills1_idx` (`Skills_id` ASC) VISIBLE,
  PRIMARY KEY (`Persona_id`, `Skills_id`),
  CONSTRAINT `fk_Persona_Skills_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Skills_Skills1`
    FOREIGN KEY (`Skills_id`)
    REFERENCES `mydb`.`Skills` (`idSkills`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona_Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona_Proyecto` (
  `proyecto_id` INT NOT NULL,
  `Persona_id` INT NOT NULL,
  INDEX `fk_Persona_Proyecto_Proyectos1_idx` (`proyecto_id` ASC) VISIBLE,
  PRIMARY KEY (`proyecto_id`, `Persona_id`),
  INDEX `fk_Persona_Proyecto_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Proyecto_Proyectos1`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `mydb`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Proyecto_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
